<?php

function nerd_community_views_default_views_alter(&$views) {
  /** @var view $view */
  $view =& $views['cod_community_attendees'];
  if($view) {
    /** @var views_display $display */
    $display = $view->display['block'];
    $fields = $view->get_items('field', 'block');

    foreach($fields as $field) {
      if($field['id'] != 'picture') {
        $view->set_item('block', 'field', $field['id'], NULL);
      }
      else {
        $field['image_style'] = 'x-small';
        $view->set_item('block', 'field', $field['id'], $field);
      }
    }
    $arg = $view->get_item('default', 'argument', 'gid');
    $arg['default_argument_type'] = 'cod_events_default_event';
    $arg['default_action'] = 'default';
    $view->set_item('default', 'argument', 'gid', $arg);
    $view->display['block']->display_options['title'] = 'Community (@count)';
    $view->display['block']->display_options['defaults']['title'] = FALSE;//
  }
}