<?php

/**
 * Adding menu links to Secondary navigation menu
 */

function nerd_homepage_update_7000() {
  $link = array(
    'link_title' => 'Learn',
    'link_path' => 'node/105',
    'menu_name' => 'menu-secondary-navigation',
    'weight' => 0,
  );
  menu_link_save($link);

  $link = array(
    'link_title' => 'Summit',
    'link_path' => 'node/1',
    'menu_name' => 'menu-secondary-navigation',
    'weight' => 3,
  );
  menu_link_save($link);

}
